[book]
title       = 'Ember Documentation'
description = 'The official documentation of Ember at The Cooper Union for the Advancement of Science and Art'
language    = 'en'
src         = 'docs'

[build]
build-dir = 'build/docs'

[output.html]
mathjax-support    = true
no-section-label   = true
git-repository-url = 'https://github.com/CooperUnion/ember'
