#ifndef DBW_NODE_PINS_H
#define DBW_NODE_PINS_H

/* LEDs */
#define NODE_BOARD_PIN_LED1 21
#define NODE_BOARD_PIN_LED2 26

/* CAN */
#define NODE_BOARD_PIN_CANTX 39
#define NODE_BOARD_PIN_CANRX 38

#endif
